@startuml
start
:Log in as User;
:Choose case management option;
if (Create Case?) then (yes)
   :createCase();
elseif (Update Case?) then (yes)
   :updateCase();
else (Delete Case?)
   :deleteCase();
endif
:Log out;
stop
@enduml
